Implement "continuous" ravens.
google-research/ravens pull request #11
Opened 2021-07-01 01:46 UTC by kevinzakka

This PR implements a continuous version of the environments and tasks, which allows us to generate dense trajectories. Specifically it contains:

* A `ContinuousEnvironment` class which subclasses the base `environment.Environment` class and eliminates the "do-it-in-1-step" `PickPlace` and `push` primitives.
* Adds a `continuous` kwarg to each instance of `Task` which should be toggled when using `ContinuousEnvironment`.
* Implements a continuous version of the oracle which uses `planners.PickPlacePlanner` for pick-and-place tasks and `planners.PushPlanner` for pushing tasks to generate intermediate actions given the pick and place poses generated by the discrete version of the oracle. The base `Planner` class is implemented via splines.

Here is some example code to illustrate the new API, which closely mimics the discrete one:

```python
env = environment.ContinuousEnvironment(ASSETS_PATH)
task = tasks.StackBlockPyramid(continuous=True)
env.set_task(task)
env.seed(1)
agent = task.oracle(env)  # This is now an instance of `ContinuousOracle`.
obs = env.reset()

info = None
done = False
for i in range(100):
    act = agent.act(obs, info)
    obs, rew, done, info = env.step(act)
    if done:
        print(f"Done at step {i}. Exiting.")
        break
```

This generates the following trajectory for the `StackBlockPyramid` task:

https://user-images.githubusercontent.com/10518920/124039895-ac213780-d9b8-11eb-91a2-97577074bbe7.mp4

You can also increase the density of the steps generated by the oracle, which allows you to generate more intermediate observations. Here is a second demonstration generated via `agent = task.oracle(env, num_steps_per_seg=5)`:

https://user-images.githubusercontent.com/10518920/124040871-9ad92a80-d9ba-11eb-9c6b-524be81f5e56.mp4

2021-07-01 01:47 UTC, kevinzakka commented
@googlebot I signed it!

2021-07-02 01:58 UTC, andyzeng approved these changes
Excellent contribution Kevin! As always.

2021-07-02 03:48 UTC, ayzaan requested changes
Thank Kevin this is great! there's some lint errors from our internal linter, added a few comments to resolve some of those.

2021-07-02 03:48 UTC, ayzaan commented on ravens/tasks/tasks_test.py
>  from ravens.environments import environment
Please revert the formatting changes in this file (move back to 2 space indent and single quotes for strings)

2021-07-02 03:48 UTC, ayzaan commented on ravens/tasks/task.py
> +from ravens.tasks import planners
```suggestion
from ravens.tasks import planners
from ravens.tasks import primitives
```

import ordering

2021-07-02 03:48 UTC, ayzaan commented on ravens/tasks/planners.py
> +    def _preprocess_poses(self, *poses):
```suggestion
    def _preprocess_poses(cls, *poses):
```

Should be cls since it's a classmethod.

2021-07-02 03:48 UTC, ayzaan commented on ravens/tasks/planners.py
> +    def _postprocess_poses(self, poses, xnew):
```suggestion
    def _postprocess_poses(cls, poses, xnew):
```

Should be cls since it's a classmethod.

2021-07-02 03:48 UTC, ayzaan commented on ravens/tasks/planners.py
> +        self.poses = None
```suggestion
        self.poses = []
```

Probably better to make this an empty list, our linter is complaining: `Non-iterable value self.poses is used in an iterating context [not-an-iterable]`

2021-07-02 14:33 UTC, merged

2021-07-02 14:36 UTC, ayzaan commented
Hey @kevinzakka, I was actually able to apply the linter fixes internally and merge the PR that way. Thanks for the contribution!