Add option to use EGL rendering for Linux systems.
google-research/ravens pull request #14
Opened 2021-07-06 03:16 UTC by kevinzakka

By default, the `Environment` class was using openGL hardware accelerated rendering. By switching to EGL rendering if using a Linux system, you can get an approximately 10x speedup in each call to the `env.step` method (9.83x to be precise.) This patch also fixes a visual bug in the spatula URDF which was missing a material definition.

Tested on my Ubuntu 20.04 machine with a RTX 2080ti:

| Renderer       | Mean                | Std dev               |
|----------------|---------------------|-----------------------|
| Default openGL | 0.2252595923267878  | 0.03675561883686646   |
| EGL            | 0.02291664930695262 | 0.0037472464227214205 |

Speedup = 9.83x

2021-08-13 20:31 UTC, kevinzakka commented
@ayzaan Would be awesome if this could get this merged!

2021-08-17 21:07 UTC, ayzaan commented
Hi Kevin, yes when I tried running this internally it didn't work out of the box. I can take a look again and see if I can get it running properly.

2021-08-17 21:08 UTC, ayzaan requested changes
Can you revert ravens/environments/assets/ur5/spatula/spatula-base.urdf?
Seems like that may have been an accidental change in this PR.

EDIT: ah sorry didn't see that part of your message. Maybe let's split that into a separate PR?

2021-08-17 21:40 UTC, kevinzakka commented
@ayzaan Done, made a separate PR for the spatula bugfix #17.

2021-08-24 18:12 UTC, merged